#!/bin/bash

daemon=hpm
daemon_pid=/run/$daemon.pid
log_file=/var/log/$daemon.log

if [ "$EUID" -ne 0 ]
  then echo "Please run as root or use sudo $0"
  exit 255
fi

echo "Trying to kill running '$daemon' to stop it..."
if [ ! -e $daemon_pid ]
then
    killall -e $daemon
else
    kill `cat $daemon_pid`
    rm -f $daemon_pid
fi
sleep 1
/etc/cron.hourly/move-hpm-log
echo "Here is the log:"
tail -n 30 $log_file
